### ISSUE TITLE
git checkout in windows machine

### ISSUE THREAD

**Issue by natacski** [Code-the-Dream-School/CtD-Week-1-Git-Assignment#3]
Hello, I got stuck when trying to create a git branch for my repository called lesson1. After adding git checkout -b lesson1, I got an error that says "not a git repository (or any of the parent directories): .git. Any advice? Thanks!
I am attaching a screenshot
<img width="440" alt="1" src="https://user-images.githubusercontent.com/63830641/83806351-5f691100-a67f-11ea-85ff-a11177b5aa4c.png">

**Comment by smykserhi** [comment]
You need move inside folder web-basics-1-week-1-********
type 'cd web' then push tab for autocomplete and hit enter.

**Comment by natacski** [comment]
@smykserhi That's correct! I forgot to open that folder. Thank you for your reply! :)
